a = input()
b = int(input())
c = int(input())
d = int(input())
e = int(b * c)
f = int(d - e)
print("Чек")
print(f"{a} - {c}кг - {b}руб/кг")
print(f"Итого: {e}руб")
print(f"Внесено: {d}руб")
print(f"Сдача: {f}руб")
